-- MySQL Script generated by MySQL Workbench
-- Thu Jul 21 08:41:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tag400`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag400` (
  `idtag400` INT NOT NULL,
  `event` DOUBLE NULL,
  PRIMARY KEY (`idtag400`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Options` (
  `idOptions` INT NOT NULL,
  `modMag` TINYINT NULL,
  PRIMARY KEY (`idOptions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tagmandatory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tagmandatory` (
  `idtagmandatory` INT NOT NULL,
  `isactivateTag` TINYINT NULL,
  `tagmandatorycol` VARCHAR(45) NULL,
  `tag400_idtag400` INT NOT NULL,
  `Options_idOptions` INT NOT NULL,
  PRIMARY KEY (`idtagmandatory`),
  INDEX `fk_tagmandatory_tag4001_idx` (`tag400_idtag400` ASC) VISIBLE,
  INDEX `fk_tagmandatory_Options1_idx` (`Options_idOptions` ASC) VISIBLE,
  CONSTRAINT `fk_tagmandatory_tag4001`
    FOREIGN KEY (`tag400_idtag400`)
    REFERENCES `mydb`.`tag400` (`idtag400`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagmandatory_Options1`
    FOREIGN KEY (`Options_idOptions`)
    REFERENCES `mydb`.`Options` (`idOptions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `idtag` INT NOT NULL,
  `modele` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `format` VARCHAR(45) NULL,
  `tagmandatory_idtagmandatory` INT NOT NULL,
  PRIMARY KEY (`idtag`),
  INDEX `fk_tag_tagmandatory_idx` (`tagmandatory_idtagmandatory` ASC) VISIBLE,
  CONSTRAINT `fk_tag_tagmandatory`
    FOREIGN KEY (`tagmandatory_idtagmandatory`)
    REFERENCES `mydb`.`tagmandatory` (`idtagmandatory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
